name: Deploy report to gh-pages
description: Deploy report to gh-pages branch

inputs:
  directory-to-deploy:
    description: 'path to the directory to deploy'
    required: true

runs:
  using: composite
  steps:
      
    - name: Set a timestamp
      id: timestampid
      # this will store current time with UTC in outputs.timestamp (eg of value: 20231028_233147Z)
      run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT" 
      shell: bash
      
    - name: Deploy reports
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ inputs.directory-to-deploy }}"
        destination_dir: ${{ steps.timestampid.outputs.timestamp }}

    - name: Write URL in summary
      run: echo "### Test results (link available after 20 secs) - https://${{ github.repository_owner }}.github.io/playwright-parameterized-projects/${{ steps.timestampid.outputs.timestamp }}/" >> $GITHUB_STEP_SUMMARY
      shell: bash

